api/urls.py
from django.urls import path

from api.views import PlantAPIView, AttributesAPIView, ChangePasswordAPIView, CustomAttributeView

app_name = "api"

urlpatterns = [
    path("plants/", PlantAPIView.as_view(), name="get_plants"),
    path("attributes/", AttributesAPIView.as_view(), name="get_attributes"),
    path("custom_attributes/", CustomAttributeView.as_view(), name="custom_attributes"),
    path("change_password/", ChangePasswordAPIView.as_view(), name="change_password"),
]

soil/urls.py
from celery_yandex_serverless.django import worker_view_factory
from django.conf import urls
from django.contrib import admin
from django.urls import path, include

from soil.celery import app
from web.views import Page404View, Page500View

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("web.urls")),
    path("api/", include("api.urls")),
    path("worker/<str:key>/", worker_view_factory(app)),
]

# requires DEBUG = False
urls.handler404 = Page404View.as_view()
urls.handler500 = Page500View.as_view()

web/forms/plant.py
from typing import Iterable

from django import forms
from django.db.models import Q
from django.utils.translation import gettext_lazy as _
from eav.models import Entity, Value

from web.mappings import taxa, suffixes
from web.models import Taxon, Plant
from web.services import create_plant_number

LEVEL = {
    0: "phylum",
    1: "class",
    2: "order",
    3: "family",
    4: "genus",
}


def modernization_dict(classification):
    counter, level_numb = 1, 0
    dct = {}
    for field, name in classification.items():
        if LEVEL[level_numb] not in dct and counter < 2:
            dct[LEVEL[level_numb]] = [name]
            counter += 1
        else:
            dct[LEVEL[level_numb]].append(name)
            counter = 1
            level_numb += 1
    return dct


def fill_out_taxon_parents(dct: dict, taxa: Iterable) -> None:
    """method fills out Taxon table 'parent_id' columns according to plant hierarchy"""
    created_taxa = {
        (taxon.level, taxon.title, taxon.latin_title): taxon.id for taxon in Taxon.objects.bulk_create(taxa)
    }
    keys = list(dct.keys())
    for key in range(len(keys) - 1):
        taxon = dct[keys[key]]
        taxon_id = taxon.id or created_taxa.get((taxon.level, taxon.title, taxon.latin_title))
        dct[keys[key + 1]].parent_id = taxon_id
    Taxon.objects.bulk_update(dct.values(), fields=["parent_id"])


def make_chain(classification):
    dct = modernization_dict(classification)
    taxa_dct = dict.fromkeys(dct)
    parent = Taxon.objects.filter(level="kingdom").first()
    created_taxa = []
    for level, names in dct.items():
        obj = Taxon.objects.filter(Q(level=f"{level}") & Q(title=names[0]) & Q(latin_title=names[1])).first()
        if not obj:
            parent = Taxon(parent_id=getattr(parent, "id", None), level=level, title=names[0], latin_title=names[1])
            created_taxa.append(parent)
        else:
            obj.parent_id = getattr(parent, "id", None)
            parent = obj
        taxa_dct[level] = parent
    fill_out_taxon_parents(taxa_dct, created_taxa)
    return parent


class PlantForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.label_suffix = ""
        for attr, value in self.fields.items():
            self.fields[attr].widget.attrs.update({"class": "form-control", "placeholder": "smt"})

    class Meta:
        model = Plant
        fields = "__all__"
        exclude = ["number", "genus", "digitized_at", "organization"]
        labels = {
            "name": _("Наименование растения"),
            "latin_name": _("Латинское наименование растения"),
            "number": _("Уникальный номер"),
            "organization": _("Организация"),
            "genus": _("Род (лат.)"),
        }
        error_messages = {
            "number": {
                "unique": _("Проверьте, пожалуйста, уникальность введенного вами номера"),
            },
        }

    def is_valid(self):
        return (
            super(PlantForm, self).is_valid()
            and self.initial["attr_form_view"].is_valid()
            and self.initial["form_classification"].is_valid()
        )

    @staticmethod
    def prepare_bulk_edit_eav_fields(plant: Plant, attrs: dict) -> tuple[list, list, set]:
        obj = Entity(plant)
        previous_values: dict = {
            val.attribute.slug: val for val in Value.objects.prefetch_related("attribute").filter(entity_id=plant.id)
        }
        created_values: list = []
        updated_values: list = []
        updated_fields: set = set()
        for attribute in obj.get_all_attributes():
            # if attribute wasn't filled out by user, skip it
            if attrs[attribute.slug] is None or attrs[attribute.slug] == "":
                continue
            # get current custom attribute value
            current_value = getattr(previous_values.get(attribute.slug), f"value_{attribute.datatype}", None)
            if current_value and current_value != attrs[attribute.slug]:
                # current value isn't equals to form attribute value => should update attribute value
                setattr(previous_values.get(attribute.slug), f"value_{attribute.datatype}", attrs[attribute.slug])
                updated_values.append(previous_values[attribute.slug])
                # bulk_update() method requires "fields" param
                updated_fields.add(f"value_{attribute.datatype}")
            # current value is None
            # it means that attribute value is filled out for the first time(need to create it)
            elif current_value is None:
                created_values.append(
                    Value(
                        **{f"value_{attribute.datatype}": attrs[attribute.slug]},
                        entity_id=plant.id,
                        attribute=attribute,
                        # redundant column
                        # if assign value 7 to entity_ct_id, it will work fine
                        entity_ct_id=7,
                    )
                )
        return created_values, updated_values, updated_fields

    def save(self, *args, **kwargs):
        if not self.instance.number:
            self.instance.number = create_plant_number()
        self.instance.organization = self.initial["user_organization"]
        plant = super().save(*args, **kwargs)
        attrs = self.initial["attr_form_view"].cleaned_data
        classification = self.initial["form_classification"].cleaned_data
        genus = Taxon.objects.filter(latin_title=classification["genus_latin_title"], level="Genus").first()
        if not genus:
            genus = make_chain(classification)
        plant.genus = genus
        created_values, updated_values, updated_fields = self.prepare_bulk_edit_eav_fields(plant, attrs)
        if created_values:
            Value.objects.bulk_create(created_values)
        if updated_values:
            Value.objects.bulk_update(updated_values, fields=updated_fields)
        plant.save()
        return plant


class TaxonForm(forms.Form):
    _suffixes = suffixes
    _taxa = taxa

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.label_suffix = ""
        for attr, value in self.fields.items():
            self.fields[attr].widget.attrs.update({"class": "form-control", "placeholder": "smt", "list": f"{attr}"})

    for taxon in _taxa:
        for key, value in _suffixes.items():
            locals()[taxon + "_" + key] = forms.CharField(label=_taxa[taxon] + value)

web/forms/profile.py
from django import forms

from web.models import Staff


class ProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.label_suffix = ""
        self.fields["email"].widget.attrs["readonly"] = ""
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
            visible.field.widget.attrs["placeholder"] = "placeholder"

    class Meta:
        model = Staff
        widgets = {"email": forms.EmailInput()}
        fields = ("surname", "name", "email")
        readonly_fields = ("email",)

web/views/plant.py
from django.views.generic import DetailView

from web.models import Plant


class PlantDetailView(DetailView):
    model = Plant
    template_name = "web/plant.html"
    context_object_name = "plant"
    slug_field = "number"
    slug_url_kwarg = "number"

    def get_context_data(self, **kwargs):
        return {
            **super(PlantDetailView, self).get_context_data(**kwargs),
            "latin_name": self.latin_name,
            "name": self.name,
        }

    def get_object(self, queryset=None):
        obj = super(PlantDetailView, self).get_object(queryset)
        self.latin_name = obj.latin_name
        self.name = obj.name
        return obj.to_dict()

web/views/plants.py
from django.http import Http404
from django.shortcuts import redirect
from django.views.generic import FormView, RedirectView, TemplateView

from web.forms import XlsxColumnsForm
from web.services.url import build_origin_from_request
from web.tasks import export_to_excel


class PlantsListView(TemplateView, FormView):
    template_name = "web/plants.html"
    form_class = XlsxColumnsForm


class XlsxColumnsView(RedirectView):
    """use RedirectView to define only 'get' request method
    - remaining methods except 'post' have the same response"""

    def get(self, request, *args, **kwargs):
        raise Http404

    def post(self, request, *args, **kwargs):
        form = XlsxColumnsForm(request.POST)
        if form.is_valid():
            origin = build_origin_from_request(request)
            export_to_excel.delay(
                origin=origin,
                user_id=request.user.id,
                columns=form.cleaned_data.get("columns"),
                filters=request.GET.urlencode(),
            )
        return redirect("plants")

web/views/profile.py
from http import HTTPStatus

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, Http404
from django.urls import reverse_lazy
from django.views.generic import UpdateView, RedirectView

from web.forms import ProfileForm
from web.models import Staff
from web.services.password import process_password_change_request


class ProfileFormView(LoginRequiredMixin, UpdateView):
    template_name = "web/profile.html"
    form_class = ProfileForm
    model = Staff
    success_url = reverse_lazy("profile")

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        response = super().form_valid(form)
        # Checking if the request wasn't sent via jQuery's Ajax
        if not self.request.headers.get("X-Requested-With") == "XMLHttpRequest":
            return response
        return JsonResponse({"success": True})

    def form_invalid(self, form):
        # Checking if the request wasn't sent via jQuery's Ajax
        if not self.request.headers.get("X-Requested-With") == "XMLHttpRequest":
            return super().form_invalid(form)
        return JsonResponse(form.errors, status=HTTPStatus.NOT_FOUND)


class ChangePasswordView(RedirectView):
    url = reverse_lazy("profile")

    def get(self, request, *args, **kwargs):
        changed = process_password_change_request(request)

        if not changed:
            raise Http404

        messages.success(request, "Вы успешно изменили пароль")
        return super().get(request, *args, **kwargs)

web/templates/web/auth.html
{% extends 'web/base.html' %}

{% block body %}
    <div class="container d-flex align-items-center justify-content-center">
        <div class="form w-25 mx-auto border border-light border-3 p-3">
            <div class="text-center">
                <h3>Авторизация</h3>
            </div>
            {% if not user.is_authenticated %}
                <form action="" method="post">
                    {% csrf_token %}
                    {% include 'web/form/form_with_errors.html' %}
                    <div class="text-center">
                        <button class="btn btn-success mt-3 w-100">Войти</button>
                    </div>
                </form>
            {% else %}
                <div class="text-center">
                    <p class="m-3">Вы уже авторизованы</p>
                    <a class="btn btn-danger" href="{% url 'logout' %}">Выйти</a>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

web/templates/web/base.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    {% block styles %}
        <link rel="stylesheet" href="{% static 'web/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'web/css/style.css' %}?">
    {% endblock %}

    <title>{% block title %}Soil DB{% endblock %}</title>
</head>
<body>
<div class="wrapper">
    <header>
        {% include "web/snippets/navbar.html" %}
    </header>
    <div class="container-fluid">
        {% block body %}{% endblock %}
        {% block messages %}
            {% include "messages.html" %}
        {% endblock %}
    </div>
    <footer class="d-flex align-items-center justify-content-center position-sticky top-100">
        © KFU ITIS, 2022-2023
    </footer>
</div>
{% block scripts %}
    <script src="{% static 'web/js/jquery.min.js' %}"></script>
    <script src="{% static 'web/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'web/js/iconify-icon.min.js' %}"></script>
    <script src="{% static 'web/js/script.js' %}?"></script>
{% endblock %}
</body>
</html>

web/templates/web/base_error.html
{% extends "web/base.html" %}
{% load static %}
{% block title %}
    {{ title }}
{% endblock %}
{% block styles %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static "web/errors.css" %}">
{% endblock %}
{% block body %}
    <main class="wrapper_error">
        <div class="description_error">
            <img src="{% static image %}" alt="" class="error__image">
            <span class="error__code">{{ status_code }}</span>
            <span class="error__header">
                {{ title }}.
            </span>
            <span class="error__text">
                {{ text|safe }}
            </span>
            {% block button %}{% endblock %}
        </div>
    </main>
{% endblock %}

web/templates/web/plant.html
{% extends 'web/base.html' %}
{% load static %}
{% load soil %}

{% block styles %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'web/css/plant.css' %}">
{% endblock %}

{% block body %}
    <div class="flex-wrapper">
        <div class="row">
            <div class="col-10">
                <h1 class="title">{{ name }} ({{ latin_name }})</h1>
            </div>
            {% if plant.Организация == request.user.organization %}
                <div class="col-2 d-flex justify-content-center align-items-center">
                    <a class="title h1 mx-1 soil-icon" title="Редактировать растение"
                            onclick="document.location='{% url 'plant_update' plant|getattr:"Уникальный номер" %}'">
                        <iconify-icon icon="material-symbols:edit"></iconify-icon>
                    </a>
                    <button class="title h1 mx-1 soil-icon" data-bs-toggle="modal"
                            data-bs-target="#modal_delete" type="button" title="Удалить растение">
                        <iconify-icon icon="mdi:garbage-can"></iconify-icon>
                    </button>
                </div>
            {% endif %}
        </div>
        <table class="table table-hover table-color table-bordered border-light rounded-4">
            <thead class="thead-dark">
                <tr class="content-align">
                    <th scope="col">Характеристика</th>
                    <th scope="col">Значение</th>
                </tr>
            </thead>
            <tbody>
            {% for key, value in plant.items %}
                <tr class="content-align">
                    <td>{{ key }}</td>
                    <td>{{ value }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="modal fade" id="modal_delete" tabindex="-1">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5">Удаление растения: {{ plant.Вид }}</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                            aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <span>Вы действительно хотите удалить <strong>{{ plant.Вид }}</strong>?</span>
                </div>
                <div class="modal-footer">
                    <form method="POST" action="{% url 'plants_delete' plant|getattr:"Уникальный номер" %}">
                        {% csrf_token %}
                        <button class="btn btn-success">Подтвердить</button>
                    </form>
                    <button type="button" class="btn btn-secondary"
                            data-bs-dismiss="modal">Отмена
                    </button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

web/templates/web/plant_form.html
{% extends 'web/base.html' %}
{% load static %}
{% load soil %}
{% block title %}
    {% if number %}
        Редактирование растения
    {% else %}
        Добавление растения
    {% endif %}
{% endblock %}
{% block body %}
    {% if not is_success %}
        <div id="app">
            <div class="container d-flex justify-content-center align-items-center">
                <div class="card w-75 my-4">
                    <div class="card-body">
                        <h5 class="card-title">{% if number %}Редактирование{% else %}
                            Новое растение{% endif %}
                        </h5>
                        <form action="" method="post" id="plant_form">
                            {% csrf_token %}
                            {% suggestions form_classification taxon_levels %}
                            {% include 'web/form/form_with_errors.html' %}
                            {% include 'web/form/form_with_errors.html' with form=attr_form_view %}
                            <div class="input-group has-validation" v-for="attr in newAttrs">
                                <div class="form-floating mt-3">
                                    <input :type="typeMapping[attr.type_attr]" :name="attr.slug_name" class="form-control"
                                            :step="attr.type_attr === 'float' ? 'any' : 1"
                                           placeholder="smt" :id="`id_${attr.slug_name}`">
                                    <label :for="`id_${attr.slug_name}`">[[ attr.name_attr ]]</label>
                                </div>
                                <div class="invalid-feedback"></div>
                            </div>
                            <button type="button" class="btn btn-outline-success mt-3" data-bs-toggle="modal"
                                    data-bs-target="#attribute_modal_window">
                                Добавить атрибут
                            </button>
                            <br>
                            <button type="submit" class="btn btn-success mt-3">{% if number %}Сохранить{% else %}
                                Добавить{% endif %}
                            </button>
                        </form>
                        <br>
                    </div>
                </div>
            </div>

            <!-- Модальное окно -->
            <div class="modal fade" id="attribute_modal_window" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Добавление атрибута</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
                        </div>
                        <div class="modal-body pt-0">
                            <form action="" method="post" id="attr_form">
                                <div class="input-group has-validation name-attr">
                                    <div class="form-floating mt-3">
                                        <input v-model="form.name_attr" type="text" class="form-control" placeholder="smt" required id="attr_name_id">
                                        <label for="attr_name_id">Название</label>
                                    </div>
                                    <div class="invalid-feedback"></div>
                                </div>
                                <div class="input-group has-validation type-attr">
                                    <div class="form-floating mt-3">
                                        <select v-model="form.type_attr" id="type_attr_id" class="form-select">
                                            <option value="text">Текст</option>
                                            <option value="date">Дата</option>
                                            <option value="float">Число с плавающей запятой</option>
                                            <option value="int">Целое число</option>
                                        </select>
                                        <label for="type_attr_id">Тип данных</label>
                                    </div>
                                    <div class="invalid-feedback"></div>
                                </div>
                            </form>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-success" @click="createAttr">Добавить</button>
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <h1>Вы успешно добавили растение</h1>
    {% endif %}
{% endblock %}
{% block scripts %}
    {{ block.super }}
    <script src="{% static 'web/js/vue.js' %}"></script>
    <script>
        const { createApp } = Vue

        createApp({
            delimiters: ['[[', ']]'],
            data() {
                return {
                    isAttrFormVisible: false,
                    form: {
                        name_attr: "",
                        type_attr: "text",
                    },
                    newAttrs: [],
                    typeMapping: {
                        int: "number",
                        float: "number",
                        text: "text",
                        date: "date",
                    }
                }
            },
            methods: {
                async createAttr() {
                    const attrCreatePath = "{% url 'api:custom_attributes' %}";
                    try {
                        const response = await fetch(attrCreatePath, {
                            method: 'POST',
                            headers: {
                                'Content-Type': 'application/json',
                                'X-CSRFToken': '{{ csrf_token }}'
                            },
                            body: JSON.stringify({
                                name_attr: this.form.name_attr,
                                type_attr: this.form.type_attr
                            }),
                        });
                        const data = await response.json();
                        this.newAttrs.push(data);
                        this.resetAttrForm();
                        console.log(data)
                    } catch (e) {
                        console.error(e);
                    }
                },
                resetAttrForm() {
                    this.form.name_attr = "";
                    this.form.type_attr = "text";
                    $('#attribute_modal_window').modal('hide');
                }
            }
        }).mount('#app')
    </script>
{% endblock %}

web/templates/web/plants.html
{% extends "web/base.html" %}
{% load static %}

{% block title %}Главная страница{% endblock %}

{% block styles %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'web/css/plant.css' %}?">
{% endblock %}

{% block body %}
    {% include "web/snippets/popup-xlsx-form.html" %}
    <div id="app"></div>
    <input type="hidden" value="{{ user.is_authenticated }}" id="isAuthenticated">
    <link rel="stylesheet" href="{% static 'web/frontend_vue/dist/assets/index.css' %}?">
    <script type="module" src="{% static 'web/frontend_vue/dist/assets/index.js' %}?"></script>
{% endblock %}

web/templates/web/profile.html
{% extends "web/base.html" %}
{% load static %}
{% load soil %}

{% block title %}Профиль{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-3"></div>
            <div class="col-6">
                <div class="card my-4">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-10"><h4 class="card-title">Профиль</h4></div>
                            <div class="col-2">
                                <a href="{% url 'logout' %}" class="h3 mx-1 soil-icon float-end" title="Выйти">
                                    <iconify-icon icon="material-symbols:logout-rounded"></iconify-icon>
                                </a>
                            </div>
                        </div>
                        <hr class="mt-0">
                        <h5 class="mb-0">Персональная информация</h5>
                        <form method="post" class="mb-2" id="profile_form">
                            {% csrf_token %}
                            {% include 'web/form/form_with_errors.html' %}
                            <div class="row mt-3">
                                <button id="save" class="btn btn-success col mx-3">
                                    Сохранить
                                </button>
                                <button type="reset" class="btn btn-secondary col me-3">
                                    Сбросить
                                </button>
                            </div>
                        </form>
                        <hr>
                        <h5 class="mb-0">Смена пароля</h5>
                        <form id="password_form">
                            {% csrf_token %}
                            <div class="input-group has-validation password">
                                <div class="form-floating mt-3">
                                    <input type="password" name="password" maxlength="128" class="form-control"
                                           placeholder="placeholder" id="id_password">
                                    <label for="id_password">Новый пароль</label>
                                </div>
                                <div class="invalid-feedback"></div>
                            </div>
                            <div class="row mt-3">
                                <button class="btn btn-success col mx-3">
                                    Сменить
                                </button>
                                <div class="col"></div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-3"></div>
        </div>
    </div>

    {% toast "success_toast" "Успешно!" "text-success" "Данные вашего профиля были успешно изменены" %}
    {% toast "info_toast" "Уведомление!" "text-info" "Письмо с инстукциями по изменению пароля отправлены вам на почту" %}
{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script>
        let profile_url = "{% url 'profile' %}";
        let password_url = "{% url 'api:change_password' %}";
    </script>
    <script src="{% static 'web/js/profile.js' %}?">
    </script>
{% endblock %}